version: '3.7'

services:
  db:  
    container_name: postgres
    image: postgres:latest 
    environment: 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crix-backend    

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - crix-backend 

volumes:
  postgres_data:
  redis_data:
    
networks:
  crix-backend:
